# Set the logo
--logo ubuntu

# Choose displayed information
--structure Title:OS:Kernel:Uptime:Packages:Shell:Resolution:DE:WM:Terminal:CPU:GPU:Memory

# Customize colors
--color-keys magenta
--color-title cyan

# Set a custom separator
--separator "  →  "
