#!/bin/bash

echo "Starting IP:"
read firstIP

echo "Last Octet of the last IP:"
read lastOctetIP

echo "Port Number:"
read port

# nmap -sT $firstIP-$lastOctetIP -p $port >/dev/null -oG MySQLscan

cat MySQLscan | grep open MySQLscan2

cat MySQLscan2
