#!/bin/bash

# Task 0: Simple MySQL Scanner
# Scan for open mysql port on a network.

#nmap -sT $IP_ADDRESS/RANGE -p $PORT >/dev/null -oG MySQLscan

cat MySQLscan | grep open > MySQLscan2

cat MySQLscan2
