# [general]

[env]
WINIT_X11_SCALE-FACTOR = "1.0"

[window]
dimensions = { columns = 112, lines = 34 }
#padding = {x = 4, y = 4 }
dynamic_padding = true
decorations = "buttonless"
opacity = 0.9
blur = true

[font]
size = 12.5

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "always" }
thickness = 0.30

[mouse]
hide_when_typing = true
